---
title: "Chapter 3 Homework - ggplot basics"
author: "Gavin Penttila"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,nycflights13,gapminder,socviz)
library(tidyverse)
library(gapminder)
```

## 3.13 Recreation

```{r gapminder, message = FALSE, warning = FALSE, echo = FALSE}
p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point(alpha = 0.3) + geom_smooth(method = "lm") + scale_x_log10(labels = scales::dollar) + 
  labs(x = "GDP Per Capita", y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")
```

## 3.16 Recreation

```{r gapminder1, message = FALSE, warning = FALSE, echo = FALSE}
p1 <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p1 + geom_point(mapping = aes(color = continent)) +
    geom_smooth(method = "loess") +
    scale_x_log10()
```

## Original Graph

```{r mpg, message = FALSE, warning = FALSE, echo = FALSE}
o <- ggplot(data = mpg, aes(x = displ, y = hwy, color = class)) + 
  geom_point() +  
  labs(title = "Fuel Efficiency by Engine Power",
       subtitle = "Fuel economy data from 1999 and 2008 for 38 popular models of cars",       
       caption = "See more at https://ggplot2.tidyverse.org/",
       x = "Engine power (litres displacement)",
       y = "Fuel Efficiency (miles per gallon)",
       color = "Car Type") + 
  annotate("text", x = 6, y = 40,
    label = "hwy and displ are \n negatively correlated \n (rho = -0.77, p-value < 0.001)",
    size = 3)
o
```